#
# Build
#

build { core init }

create_boot_directory

#
# Generate config
#

install_config {
<config verbose="yes" prio_levels="128">
	<parent-provides>
		<service name="LOG"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
</config>}

#
# Boot image
#

build_boot_image { core init }

append qemu_args " -nographic -smp 2"

run_genode_until "exited with exit value 0.*\n" 10
